# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c9fc1bf3ef0afefebddf367bebfb1eae778cb5162ccf6b73e3f01ad2a5e8e77debe1acfa1247b7aeb05f59179b858a3796c38580c7272b5b9c61812829ace0

test:
  secret_key_base: ed55bffe1f4a53c37d38d322276205ffe009472c2cab2060d7ae79e8b78ab61b21cb059be30466986c29575532b1eea8394da11e59cb03b50317fddf21e0384a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
